#### Creating ndarrays. it involes one dimensional, two dimensional, three diemnsional arrays and so on

In [89]:
import numpy as np
a1=np.array([1,2,3])

a11=np.array([1,
             2,
             3])

a2=np.array([[1,2,3],
            [4,5,6]])

a3=np.array([[[1,2,3],
            [4,5,6.3],
            [7,8.2,9]],
             
           [[10,11,12],
            [13,14,15],
            [16,17,18]]])

a4=np.array([[[1,2,3],
              [4,5,6]],
           
             [[7,8,9],
              [10,11,12]],
             
             [[13,14,15],
              [16,17,18]]])

In [90]:
a1,a11,a2,a3,a4

(array([1, 2, 3]),
 array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1. ,  2. ,  3. ],
         [ 4. ,  5. ,  6.3],
         [ 7. ,  8.2,  9. ]],
 
        [[10. , 11. , 12. ],
         [13. , 14. , 15. ],
         [16. , 17. , 18. ]]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]))

#### Numpy array shape, size, type & ndim details

In [91]:
a1.shape,a11.shape,a2.shape,a3.shape,a4.shape

((3,), (3,), (2, 3), (2, 3, 3), (3, 2, 3))

In [76]:
a1.size,a2.size,a3.size,a4.size

(3, 6, 18, 18)

In [92]:
a1.ndim,a11.ndim ,a2.ndim,a3.ndim,a4.ndim

(1, 1, 2, 3, 3)

In [75]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('int32'), dtype('float64'))

In [78]:
type(a1),type(a4)

(numpy.ndarray, numpy.ndarray)

#### numpy zeros,ones & empty arrays

In [54]:
a4=np.zeros([3,2,2])
a5=np.zeros((3,2,2))
a6=np.zeros((2,2))
a4,a5,a6

(array([[[0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.]]]),
 array([[[0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.]]]),
 array([[0., 0.],
        [0., 0.]]))

In [55]:
a4.ndim,a5.ndim,a6.ndim

(3, 3, 2)

In [56]:
a4.shape,a5.shape,a6.shape

((3, 2, 2), (3, 2, 2), (2, 2))

In [97]:
a11=np.ones([2,2,3])
a11

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [59]:
#array.empty requires users to fill the values.Uninitialized
# use np.empty(press shift tab to get docstring of this function)
np.empty()
a7=np.empty([2,2])
a7

array([[2.12199579e-314, 2.14321575e-312],
       [4.42682819e-321, 6.95271921e-310]])

In [47]:
# ndarray must be multidimensional, homogeneous array of fixed-size items
a8=np.array([[[1,2,3],
              [4,5,6]],
           
             [[7,8,9],
              [10,11,12]],
             
             [[13,14],
              [16,17]]])

<ipython-input-47-974fba413824>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a7=np.array([[[1,2,3],


#### numpy dot method

In [61]:
a=([1,2,3])
b=([3,2,1])
c=np.dot(a,b)
c
#it works as below
c=(1*3+2*2+3*1)

10

In [62]:
a=([[1,2],
   [2,1]])
b=([[3,4],
    [4,3]])
c=np.dot(a,b)
c
# it works like below
c=([[1*3+2*4 ,1*4+2*3],[2*3+1*4 ,2*4+1*3)

array([[11, 10],
       [10, 11]])

#### create dataframes using numpy.array

In [88]:
import pandas as pd
a1=np.array([1,2,3])

a2=np.array([[1,2,3],[4,5,6]])

df1=pd.DataFrame(a1,columns=(['a']))

df2=pd.DataFrame(a2,columns=(['a','b','c']))

df1,df2

(   a
 0  1
 1  2
 2  3,
    a  b  c
 0  1  2  3
 1  4  5  6)

#### Range Arrays

In [101]:
range_array=np.arange(start=1,stop=10)

range_array_2=np.arange(start=1,stop=10,step=2)

range_array_3=np.arange(start=1,stop=100,step=2**2)
range_array,range_array_2,range_array_3

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 3, 5, 7, 9]),
 array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
        69, 73, 77, 81, 85, 89, 93, 97]))

#### Random Arrays

In [162]:
#random.randint
random_array1=np.random.randint(1,10)

random_array2=np.random.randint(1,10,size=(2,2))

random_array1,random_array2

(7,
 array([[9, 6],
        [6, 5]]))

#### random using random_seed

In [175]:
#random seed gives single consistent ndarray values for each seed value. 
#This helps to validate and compare the output across multiple users or environments.
# Random.seed applies for all numpy random functions
np.random.seed(1)
random_array21=np.random.randint(1,10,size=(2,2))
random_array21

array([[6, 9],
       [6, 1]])

In [126]:
type(random_array1),type(random_array2)

(int, numpy.ndarray)

In [142]:
#random.random
random_array3=np.random.random

random_array4=np.random.random(3)

random_array5=np.random.random((3,3))

random_array3,random_array4,random_array5

(<function RandomState.random>,
 array([0.48013642, 0.12276416, 0.33847232]),
 array([[0.71827649, 0.01166456, 0.33367748],
        [0.0529965 , 0.49947937, 0.95047422],
        [0.30454076, 0.00585046, 0.78555391]]))

In [143]:
type(random_array4),type(random_array5)

(numpy.ndarray, numpy.ndarray)

In [155]:
#random.rand
random_array6=np.random.rand(3)

random_array7=np.random.rand(3,3)

random_array6,random_array7

(array([0.27663943, 0.62590611, 0.96762006]),
 array([[0.55872328, 0.47277067, 0.10630768],
        [0.62340266, 0.47655386, 0.53316989],
        [0.95829089, 0.16431599, 0.14570431]]))

In [177]:
#unique array 
a9=np.array([[1,2,2],
            [3,4,2]])
np.unique(a9)

array([1, 2, 3, 4])